### ISSUE TITLE
Add command line arguments

### ISSUE THREAD

**Issue by worc4021** [CharlesWB/LicenseStatus#11]
Hi,

This utility is quite handy. However, it would be great if it accepted arguments so that I can create a shortcut which holds the information that I otherwise have to supply every time I open it and then mustn't close.

Cheers
Manuel

**Comment by CharlesWB** [comment]
Thanks for the idea.

What I'm uncertain about is that it should remember all of your settings between sessions. Settings such as host name, port number, lmstat location. I don't yet know of a reason why they wouldn't be remembered.

If that's not the issue you're having, can you provide more details about what information is not remembered.

**Comment by worc4021** [comment]
I see! Something is being weird on my side then. whenever I run the application I have to fill in the entire licence information. Hence we have a readme in the same folder to copy paste all the configuration into the application. Is the buffering of the information a newish feature?

**Comment by CharlesWB** [comment]
No, saving the settings between sessions has always been there.

License Status uses the .NET application settings functionality. This works by saving the data in your local app data folder. Specifically, the path would be `%LOCALAPPDATA%\Charles_W._Bozarth\`. In that folder you'd find a folder that begins with LicenseStatus.exe_, and in that folder you'd find version folder 3.7.5356.32096. And then this contains a file named user.config which contains the settings.

I'm guessing that path doesn't exist and can't be created. Is it possible your computer has access restrictions to %LOCALAPPDATA%?

You might try running License Status as administrator. Although I haven't found a reason that would require this.

**Comment by worc4021** [comment]
Fixed it. I did not actually install the application. We all just run it from a shared drive and simply using the regular installer (hence installing it on my local drive) fixed it. Maybe there is some restriction when an application is not registered or something along those lines. Now it does store the configuration. Thank you!

**Comment by CharlesWB** [comment]
Thanks. I'll look into running it that way sometime. It's possible that I could support that way of running it.
